### ISSUE TITLE
random ConcurrentModificationException

### ISSUE THREAD

**Issue by MikeSingularity** [Aroma1997/BetterChests#78] opened 2015-04-14 15:54 UTC
I've been having trouble with various crashes in my modded minecraft, so I setup a fresh install of Minecraft, Forge and BetterChests to see if it was just BetterChests or there was a synergistic effect from another mod. 

At the time of the crash I wasn't interacting with anything - was flying in creative mode.

The fml-client-latest.log was too big for pastebin to handle, I created a dropbox download with all logs and the world save, in case you needed it.

Crash Report http://pastebin.com/15yCtHnn
Complete Logs and World https://www.dropbox.com/s/rb8v6f14gj8gt91/Crash_2015-04-14_Logs_and_World.zip?dl=0

Versions:
Minecraft: 1.8
Forge: 11.14.1.1361 (FML) 8.0.73.1361 (MCP) 9.05
Aroma1997Core: 1.0.3.4
BetterChests: 1.2.0.0
No other mods installed

**Comment by Aroma1997** [comment] 2017-12-02 11:20
If my assumtions on the cause of this are correct, then it's fixed in the 1.12 version, but I won't fix it in the older versions anymore.

**Closed by Aroma1997** 2017-12-02 11:20 UTC
Labels: bug
