### ISSUE TITLE
You can place a backpack inside itself

### ISSUE THREAD

**Issue by iamtpage** [Aroma1997/BetterChests#103] opened 2018-01-17 01:08 UTC
Hi,

I accidentally placed a backpack inside itself and closed the GUI, thus losing the back forever. Is there a way to get it back? Or would it be possible to prevent a backpack from getting stored in itself?

**Comment by Aroma1997** [comment] 2018-01-17 09:14
Whenever you place a backpack in itself, it should automatically close its GUI and drop the backpack in front of you.
Are you sure you didn't just put a different backpack in your backpack or that the backpack didn't drop?

**Comment by iamtpage** [comment] 2018-01-17 16:03
I've been able to reproduce this twice so far (both times due to careless accidents). The GUI closes as stated, but the bag doesn't drop on the ground. I'll see if I can produce any errors in the console, but the bag hasn't dropped either time. Both times it was an upgrade bag (7x storage slots), not sure if that impacts anything.

**Comment by Aroma1997** [comment] 2018-01-17 19:54
Can you give me more details?
Are you in a singleplayer world or on a server? What are you doing to make this happen? What Items are in it? How can I reproduce the issue?

**Comment by iamtpage** [comment] 2018-01-17 21:06
It's on a server

Steps to reproduce:
1. Craft backpack 
2. Fill it with storage upgrades (not sure if necessary)
3. Open it
4. Shift click items into it, including the bag
5. The bag GUI is closed and not dropped as an item

**Comment by Aroma1997** [comment] 2018-01-17 21:22
I could still not reproduce the issue. Also: what versions are you using?
Could you however try to use build 136 of Aroma1997Core and see if using that fixes it?

**Comment by iamtpage** [comment] 2018-01-17 23:11
Currently running Aroma1997core-1.12.2-2.0.0.0.b135 and BetterChests-1.12.2-2.1.1.3
Here is a video that shows the bug: https://imgur.com/a/oeWIn

I'll test later tonight/tomorrow with b136

**Comment by Aroma1997** [comment] 2018-01-18 08:14
That betterchests version number is really weird. I never released a version with that version number...

**Comment by iamtpage** [comment] 2018-01-18 14:02
Sorry, I updated the comment with the actual version for BetterChests

**Comment by Aroma1997** [comment] 2018-01-18 21:23
Whoops, looks like I closed the wrong issue...

**Comment by iamtpage** [comment] 2018-01-19 20:50
I've tested this on the latest Aromacore and BetterChests version, the issue is still present

spongeforge-1.12.2-2555-7.1.0-BETA-2833
and
forge-1.12.2-14.23.1.2555-universal-server

**Comment by Aroma1997** [comment] 2018-01-19 20:51
Can you see if the issue is still present, if sponge is removed?

**Comment by iamtpage** [comment] 2018-01-19 21:00
I was able to try locally, and can confirm that without sponge installed the issue does not happen.

**Comment by Aroma1997** [comment] 2018-01-19 21:06
Can you report it to the sponge people then? I have no clue what they're doing so this doesn't work anymore...

**Closed by Aroma1997** 2018-01-19 21:06 UTC
Labels: bug

**Comment by iamtpage** [comment] 2018-01-19 21:08
Can you point to the line in your code where this is handled? That way I can reference it when I create an issue with SpongeForge

**Comment by Aroma1997** [comment] 2018-01-19 21:12
It's handled in aroma1997.core.container.elements.ContainerElementHandheld in Aroma1997Core.

**Comment by iamtpage** [comment] 2018-01-19 21:14
In the mean time, would it be possible to just make it so if the backpack GUI is open, the backpack item can't be moved in the GUI? 

This is how Thermal Expansion handles it (with satchels), and would prevent the issue from happening. That way it's future proof regardless on how Sponge handles it.

**Comment by Aroma1997** [comment] 2018-01-19 21:17
It would be possible, but adding back in another solution, that I purposely removed in the rewrite, would just not be worth my time, especially since I kow how much of a pita it is to get that working.
